In [1]:
import numpy as np
import torch 

In [6]:
t=np.array([[[0,1,2]],
           [[9,10,11]]])

In [11]:
t=torch.FloatTensor(t)

In [12]:
t=t.view([-1,3])

In [13]:
t

tensor([[ 0.,  1.,  2.],
        [ 9., 10., 11.]])

In [40]:
ft=torch.FloatTensor([[0,2,4],[1,3,1],[2,5,6]])
ft

tensor([[0., 2., 4.],
        [1., 3., 1.],
        [2., 5., 6.]])

In [43]:
a=ft.squeeze()

In [44]:
a

tensor([[0., 2., 4.],
        [1., 3., 1.],
        [2., 5., 6.]])

In [ ]:
x=torch.Tensor